### ISSUE TITLE
Add support for enum types with ':' in name

### ISSUE THREAD

**Issue by ilsotov** [Ajaxy/tinyspec#16]
Following type is invalid
```
PermissionType (
  "own:companies:write" |
  "own:documents:write" |
  "own:conversations:write" |
  "company:members:read" |
  "company:members:write" |
  "company:documents:read" |
  "company:documents:write" |
  "company:conversations:read" |
  "company:conversations:write" |
  "companies:read" |
  "companies:write" |
  "documents:read" |
  "documents:write" |
  "conversations:read" |
  "conversations:write" |
  "members:read" |
  "members:write" |
  "widgets:read" |
  "widgets:write" |
  "widgetCategories:read" |
  "widgetCategories:write" |
  "chatBot:read" |
  "chatBot:write" |
  "roles:read" |
  "roles:write" |
  "tickets:read" |
  "tickets:write" |
  "auditLogs:read" |
  "superagent"
)
```

```
Error: Definition `( "own:companies:write" | "own:documents:write" | "own:conversations:write" | "company:members:read" | "company:members:write" | "company:documents:read" | "company:documents:write" | "company:conversations:read" | "company:conversations:write" | "companies:read" | "companies:write" | "documents:read" | "documents:write" | "conversations:read" | "conversations:write" | "members:read" | "members:write" | "widgets:read" | "widgets:write" | "widgetCategories:read" | "widgetCategories:write" | "chatBot:read" | "chatBot:write" | "roles:read" | "roles:write" | "tickets:read" | "tickets:write" | "auditLogs:read" | "superagent" )` is invalid
    at parseSingleProp (node_modules/tinyspec/lib/parseProps.js:123:11)
    at parsePropsString (node_modules/tinyspec/lib/parseProps.js:47:10)
    at modelDefs.forEach (node_modules/tinyspec/lib/transformModels.js:64:41)
    at Array.forEach (<anonymous>)
    at toOpenapi (node_modules/tinyspec/lib/transformModels.js:17:13)
    at generateYaml (node_modules/tinyspec/index.js:104:42)
    at Object.<anonymous> (node_modules/tinyspec/index.js:47:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Comment by Ajaxy** [comment]
Fixed dfba3094a4efc1b6e6750d24a90329d55cbe63a0
